### ISSUE TITLE
CachingConnector::fetch should allow passing in the cache key

### ISSUE THREAD

**Issue by markchalloner** [ScriptFUSION/Porter#30]
If we allow CachingConnector to take a cache key parameter, then it can be used with existing or shared caches where the keys are not of the form CachingConnector::hash produces.

My use case for this is using existing ODM Mongo documents to cache values with the document ID being the cache key.

To maintain backward compatibility the parameter should be optional and in the event of null, CachingConnector should fallback to generating the cache key using CachingConnector::hash.

**Comment by Bilge** [comment]
It seems we need to create a `CacheKey` interface for which different cache key strategies can be used with `CachingConnector`. I think this also takes care of a [similar concern](https://github.com/ScriptFUSION/Porter/pull/29#issuecomment-286719420) raised by @samvdb.
