### ISSUE TITLE
Rate Limiter

### ISSUE THREAD

**Issue by Sarke** [ScriptFUSION/Porter#57]
Any thoughts on adding some type of rate limiter functionality, as to not clobber the servers?

**Comment by Bilge** [comment]
I currently have one at [ScriptFUSION/Async-Throttle](https://github.com/ScriptFUSION/Async-Throttle), but it's for the upcoming async version of Porter (v5). I haven't had a need to throttle synchronous connections yet, because they're inherently slow already. What's your use case?

**Comment by Bilge** [comment]
Ping @Sarke. Will close this if no feedback provided.
