### ISSUE TITLE
How I can get what went wrong at import process ?

### ISSUE THREAD

**Issue by fico7489** [ScriptFUSION/Porter#58]
For example when server return 404 not found 412  ?

**Comment by Bilge** [comment]
Depends if you're writing a provider or consuming a provider. If just consuming one, set a custom [`fetchExceptionHandler`](https://github.com/ScriptFUSION/Porter/blob/c50bc62e56993c4860b1d62819679a6c6e9ec913/src/Specification/ImportSpecification.php#L251-L263) in your `ImportSpecification`.
