### ISSUE TITLE
Laravel and CachingConnector?

### ISSUE THREAD

**Issue by 4n70w4** [ScriptFUSION/Porter#60]
How to enable CachingConnector in Laravel?

```php
    public function handle() {
        app()->bind(HttpConnector::class, CachingConnector::class);

        app()->bind(EuropeanCentralBankProvider::class, EuropeanCentralBankProvider::class);

        $porter = new Porter(app() );

        $specification = new ImportSpecification(new DailyForexRates() );
        $specification->enableCache();
        $rates = $porter->import($specification);

        foreach ($rates as $rate) {
            echo "$rate[currency]: $rate[rate]\n";
        }

    }
```

`   ScriptFUSION\Porter\Cache\CacheUnavailableException  : Cannot cache: connector does not support caching.`

**Comment by Bilge** [comment]
Sorry, I don't know anything about Laravel. The error means the connector that's being used to import `DailyForexRates` is not `CachingConnector`, but some other class. If you want to cache responses from the `HttpConnector`, you need to wrap the `HttpConnector` with the `CachingConnector`, so it would look like the following.

```php
new CachingConnector(new HttpConnector);
```

I do not know how to do this with Laravel, but essentially you need to inject `HttpConnector` inside `CachingConnector` and then inject that `CachingConnector` into `EuropeanCentralBankProvider`. Unfortunately, it seems `EuropeanCentralBankProvider` only supports `HttpConnector`, though, so we would need to fix that!

**Comment by Bilge** [comment]
This is fixed in [EuropeanCentralBankProvider](https://github.com/Provider/European-Central-Bank) version 5.
